### ISSUE TITLE
Should variation analysis build on preprocessing?

### ISSUE THREAD

**Issue by wm75** [galaxyproject/SARS-CoV-2#10]
My naive expectation was that I could use the output of the preprocessing workflow (at least the Illumina parts of it) as input to the variation analysis workflow, but this doesn't seem to be the case.

The public history seems to use input Illumina data that has been preprocessed (the stdout contains corresponding info), but it's unclear how exactly.

Is it possible to adjust the workflows to make them work together?

**Comment by nekrut** [comment]
It does build on postprocessing. It takes reads after `fastp`. We can certainly do it that way. Do you have an idea?

**Comment by wm75** [comment]
I have two alternative ideas::

1. The simple one:
    - just don't hide the fastp collection during the pre-processing workflow
    - mention it as one of the workflow outputs in the pre-processing README
    - mention it as input to the variation workflow in the variation README

    In other words, just clarify the current analysis flow.

2. Base the analysis of variation on the same non-human reads used for assembly.

    - bifurcate the preprocessing workflow after samtools view filtering of  the Illumina reads:
      * merge the data as before for assembly
      * run samtools fastx directly on the filtered collection and zip the result for the variation analysis

    The variation analysis workflow can remain unchanged, but the discovered variants and their AFs
    will  change substantially (just 168 detected variants in total, also the set of above 5% AF variants changes). The important `SRR10903401 | NC_045512 | 24323 | A | C` variant is still picked up, however (at an AF of 36%). See https://usegalaxy.eu/u/wolfgang-maier/h/ncov-variation-simple for the complete result.

    Definitely, this change requires substantially more work, but may remove some noise introduced by using what is in fact human reads.

**Comment by nekrut** [comment]
I went with idea 1:

I have pointer from pre-processing
I "unhid" fastp output in pre-processing workflow
I will add explanation to variation section
