### ISSUE TITLE
Error while running Unicycler.

### ISSUE THREAD

**Issue by ambarishK** [galaxyproject/SARS-CoV-2#117]
I am getting error while running Unicycler.

````
tput: No value for $TERM and no -T specified
Error: the paired read input files have an unequal number of reads

````
How to resolve it?

**Comment by bgruening** [comment]
> Error: the paired read input files have an unequal number of reads

This is the error. You have not provided clean paried-reads. Maybe they are corrupted or you have filtered them wrongly ...

**Comment by ambarishK** [comment]
Let me check.

**Comment by ambarishK** [comment]
Resolved.
