### ISSUE TITLE
Error while running gffread.

### ISSUE THREAD

**Issue by ambarishK** [galaxyproject/SARS-CoV-2#121]
I am getting an error while running gffread. 

````
No fasta index found for genomeref.fa. Rebuilding, please wait..
Error: sequence lines in a FASTA record must have the same length!

````

**Comment by ambarishK** [comment]
I normalized fasta file which solve above error.

Now I am getting 0 byte output while running gffread on merged gtf.

````
0 bytes
formatfastadatabase?
No fasta index found for genomeref.fa. Rebuilding, please wait..
Fasta index rebuilt.

````

**Comment by bgruening** [comment]
@ambarishK this is not an error. Can you share your history?

**Comment by ambarishK** [comment]
Sir, this is the accessible link to my history - https://usegalaxy.eu/u/ambarishk/h/de-novo

**Comment by bgruening** [comment]
@ambarishK take off the "fasta file with spliced CDS for each GFF transcript (-x cds.fa)" "protein fasta file with the translation of CDS for each record (-y pep.fa)" ... you don't have CDS records.

Then it will work.

**Comment by ambarishK** [comment]
Thank you so much sir. It worked.

Now I am moving for abundance estimation of gene expression.

I am trying to quantify them using align and estimate abundance method - a trinity tool. It askes for transcript to gene map file. I am generating gene to transcript map file using RSEM gene to transcript map tool. But quantification fails.
