### ISSUE TITLE
Incompatibility between Pre-processing and Assembly wfs

### ISSUE THREAD

**Issue by wm75** [galaxyproject/SARS-CoV-2#18]
Assembly is supposed to start with the pre-processing output, but @nekrut's assembly history shows that the input files there have been generated with Picard sam_to_fastq, while the pre-processing wf ends with `samtools fastx`.

In fact, when you try to combine the two workflows, you're getting a Unicycler error (at least on EU):
`Error: the paired read input files have an unequal number of reads`

Presumably, if using `samtools fastx`, one would have to exclude reads the mate of which isn't mapped, or similar. Alternatively, use the Picard conversion insetad-

**Comment by wm75** [comment]
Upon closer inspection, I think the fix for this would be in Step 13 of Pre-processing, the`Filter SAM or BAM` step of the mapped Illumina data:
under **Only output alignments with all of these flag bits set**, you would have to check not only *The read is unmapped*, but also *The mate is unmapped* => discarding whole read pairs if even only one of their ends maps to hg38. (`samtools fastx` relies on the FLAG bits for sorting the reads into sets 1 and 2, but cannot know that you filtered out some mates before).

Just verifying that this works on EU now.

**Comment by wm75** [comment]
Test on usegalaxy.eu was successful (https://usegalaxy.eu/u/wolfgang-maier/h/preprocessingassembly). Assembled contig lengths are the same after the modification.

So what's left to do is:

- add the _The mate is unmapped_ checkbox selection to **Only output alignments with all of these flag bits set** of Step 13 of the public Pre-processing workflow on main
- regenerate the public histories for pre-processing and assembly on main (base the latter on the unmodified outputs of pre-processing)

**Comment by nekrut** [comment]
fixed workflow and rerunning history:
correct workflow: https://usegalaxy.org/u/aun1/w/covid-19-pre-pp
correct history: https://usegalaxy.org/u/aun1/h/covid-19-pre-processing
