### ISSUE TITLE
Fix links for the workflow badges for every instance

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/SARS-CoV-2#21]
* [x] usegalaxy.org
* [ ] usegalaxy.org.au
* [x] usegalaxy.eu

**Comment by Harrystark99** [comment]
Fixed the links, opening a pull request

**Comment by Harrystark99** [comment]
@bgruening  This issue is fixed I think...

**Comment by bgruening** [comment]
Very true! Thanks.
