### ISSUE TITLE
ARTIC workflow error during Realigh Read with samtools

### ISSUE THREAD

**Issue by PHemarajata** [galaxyproject/SARS-CoV-2#210]
Hi, I ran in the the error below while running the ARTIC workflow during Realign Reads step:

sort: unrecognized option '--no-PG'
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]

Any suggestion would be highly appreciated. Thank you!

**Comment by bgruening** [comment]
@PHemarajata can you share with us your history?

**Comment by wm75** [comment]
Maybe it was a bit optimistic to not have an explicit samtools version 1.10 requirement as part of https://github.com/galaxyproject/tools-iuc/pull/3077? The --no-PG option got added to samtools sort only at that version (1.9 and lower don't have it).
@PHemarajata which Galaxy server are you seeing this on (the tool is working fine on usegalaxy.org and usegalaxy.eu)?
@bgruening Could this have something to do with the conda channel order?

**Comment by bgruening** [comment]
> @bgruening Could this have something to do with the conda channel order?

I don't think so. But wherever this workflow is running we should check the samtools version.

**Comment by PHemarajata** [comment]
I am running the workflow on my local Galaxy server. Since you guys were talking about versions, I tried changing the lofreq (for the Call Variants step) and lofreq viterbi (for the Realign Reads step) versions used in the workflow from 2.1.5 to 2.1.3.1 and the workflow was able to run to completion. I am so glad it worked. Thank you everyone for such a great tool.
