### ISSUE TITLE
Should we rename MCRA to MRCA?

### ISSUE THREAD

**Issue by wm75** [galaxyproject/SARS-CoV-2#24]
Unfortunately, I did not have time to read up on the question of which is the right acronym for *most recent common ancestor* analysis before, but from a bit of research now **MRCA** seems to be in *much* wider use (and also makes more sense). Whenever you find *MCRA* it looks more like a typo on pages that also use *MRCA*.

It would require a bit of effort though to change all occurrences of MCRA in this repo, but also in the workflow and the notebook.

**Comment by nekrut** [comment]
yes
