### ISSUE TITLE
Do we want workflow .ga files as part of the repo?

### ISSUE THREAD

**Issue by wm75** [galaxyproject/SARS-CoV-2#25]
Pro:
- each repo release and accompanying zenodo snapshot would have an unchangeable workflow file in it, which is certainly a big plus for reproducibilty
- at least with pretty-printed json .ga files we gain some rudimentary diffing of workflow versions

Con:
- extra work to keep repo versions and published workflow versions on Galaxy instances in sync

**Comment by nekrut** [comment]
i have no feelings here, we can but it is a maintenance burden

**Comment by bgruening** [comment]
Let's keep the out for now? We do have links on every page ...

**Comment by wm75** [comment]
ok for me
