### ISSUE TITLE
SRR11313490 and SRR11313499

### ISSUE THREAD

**Issue by flodebarre** [galaxyproject/SARS-CoV-2#291]
Hi, 
You may have seen Jesse Bloom's [recent preprint](https://www.biorxiv.org/content/10.1101/2021.06.18.449051v1) on the recovery of deleted SRA files. @jbloom managed to recoved most of the data from Google Cloud, except for two, SRR11313490 and SRR11313499. I Googled these IDs, and found a [dead link](https://github.com/galaxyproject/SARS-CoV-2/blob/master/genomics/4-Variation/sra.txt) to your repository, but I could find it back through the history (e.g. it is available at Latest commit f5b1766 on 28 Apr 2020). Had you by any chance downloaded the corresponding SRA data, and do you still have them? 
Thanks!

**Comment by mvdbeek** [comment]
We may have, I'll take a look.

**Comment by mvdbeek** [comment]
Unfortunately that's a GridION accession, we only downloaded the Illumina accessions at this point. I will check if we have any trace of this anyway, but I'm not hopeful :(.

**Comment by flodebarre** [comment]
🤞In case this may help, the IDs also appear [here](https://usegalaxy.eu/datasets/11ac94870d0bb33aae5314cb4e400cee/display/?preview=True).

**Comment by mvdbeek** [comment]
@bgruening can you take a look if you have the accession on .eu ?
I haven't found a collection element with those identifiers, checking HDAs now.
I've used `select * from dataset_collection_element where element_identifier = 'SRR11313490';` and `select * from history_dataset_association where name = 'SRR11313490';`.

@flodebarre I suppose at this point you've contacted the SRA, but just in case you haven't received a response we can forward your request to our contact there.

**Comment by flodebarre** [comment]
@mvdbeek I have not, but I understand that @jbloom [has](https://twitter.com/jbloom_lab/status/1407558426939387906?s=20). 

I have a related question---let me know if it is best to open another issue for it. 
Jesse Bloom found out about the missing files because there was a way to learn that they ever existed (namely, a supplementary table in [this paper](https://peerj.com/articles/9255/)). I see that the next [`sra.txt`](https://github.com/galaxyproject/SARS-CoV-2/blob/68c946614a50481ada03feb938df6b0c1d134340/genomics/sra.txt) file in your repo is listing fewer IDs than it used to. Is there a simple way to put in a single file all the SRA IDs that you ever listed for this project?

**Comment by mvdbeek** [comment]
We can go through commit-by-commit and build a set of ids, that should be possible.

**Comment by mvdbeek** [comment]
It also turns out that the dataset you referenced is from the
sars-cov-2-bot account we created for this project. The history is public
(that's why you found it), but I'm traveling now and internet is spotty.
Should have some more info for you later, but it looks like the download
for this dataset failed (like most jobs in that history).

**Comment by jbloom** [comment]
@flodebarre, I was actually able to find the two missing accessions thanks to some helpful pointers after publication of the initial pre-print. Those accessions are available as described [here](https://github.com/jbloom/SARS-CoV-2_PRJNA612766/blob/trim_primer_overlaps/config.yaml#L154-L165). 

However, these two accessions provide minimal additional information. Both are from low coverage samples, and even with the additional runs it's not possible to call meaningful genotypic information for these two samples. I am working on a revision to the pre-print that adds these two accessions, but it doesn't change any results.

I do think it could be worth systematically searching historical lists of all SARS-CoV-2 accessions that have been downloaded at various times to see if they are still available, though. Happy to help if needed.

**Comment by mvdbeek** [comment]
Here's a quick and dirty list of all accessions we've checked into git: https://gist.github.com/mvdbeek/a6add8ede9b349b0d9a47d66460400ba

**Comment by mvdbeek** [comment]
Here's a list of 6798 accessions that were checked in at one point or another to this repository and that are not anymore in the current metadata of the ENA: https://gist.github.com/mvdbeek/a9891f906489596064ae490793d9c19c

271 of those accessions were SRA accessions. 

The current metadata from the ENA I fetched via ```curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d 'result=read_run&query=tax_eq(2697049)&fields=accession%2Cbase_count%2Ccell_line%2Ccell_type%2Ccenter_name%2Cchecklist%2Ccollected_by%2Ccollection_date%2Ccountry%2Ccram_index_ftp%2Cdescription%2Cexperiment_accession%2Cexperiment_alias%2Cexperiment_title%2Cfastq_aspera%2Cfastq_bytes%2Cfastq_ftp%2Cfastq_md5%2Cfirst_created%2Cfirst_public%2Chost%2Chost_sex%2Chost_tax_id%2Cinstrument_model%2Cinstrument_platform%2Cinvestigation_type%2Cisolate%2Cisolation_source%2Clast_updated%2Clat%2Clibrary_layout%2Clibrary_name%2Clibrary_selection%2Clibrary_source%2Clibrary_strategy%2Clocation%2Clon%2Cread_count%2Crun_accession%2Crun_alias%2Csample_accession%2Csample_alias%2Csample_description%2Csample_material%2Csample_title%2Csampling_campaign%2Csampling_platform%2Csampling_site%2Cscientific_name%2Csra_aspera%2Csra_bytes%2Csra_ftp%2Csra_md5%2Cstrain%2Cstudy_accession%2Cstudy_alias%2Cstudy_title%2Csub_species%2Csub_strain%2Csubmitted_bytes%2Csubmitted_format%2Csubmitted_host_sex%2Csubmitted_sex%2Ctax_id&limit=0&format=tsv' "https://www.ebi.ac.uk/ena/portal/api/search"```

then used `grep -e  '[S|E]RR\d{7,8}'` to only get the uniq accessions. I built a set from both https://gist.github.com/mvdbeek/a6add8ede9b349b0d9a47d66460400ba and the ena meadata, then subtracted the current ena metadata from https://gist.github.com/mvdbeek/a6add8ede9b349b0d9a47d66460400ba.

I've just threwn this together real quick, and there are probably caveats (like maybe the tax id was just change), but spot checking the ENA returns records that have `Warning: Record ERR4165047 has been killed.`

Note that we may not have downloaded all of those accessions, but if you think there's something interesting in there let us know. I'll compile a list of deleted datasets we did actuallt successfully fetch, but that'll have to wait until tomorrow ...

**Comment by jbloom** [comment]
I'm not able to easily assess if any of these are of interest, but if you still have FASTQs (or SRA files or something else) for any of them, I can try aligning them to look. I have a pipeline to do this. Easiest is if there is just a CSV of the accession and then the http or ftp path where the file(s) lives, but if it isn't possible to get that then we can look at other ways to process them.

**Comment by bgruening** [comment]
@jbloom @flodebarre I have both files (SRR11313490 and SRR11313499).

[SRR11313499.fastq.gz](https://github.com/galaxyproject/SARS-CoV-2/files/6722313/SRR11313499.fastq.gz)
[SRR11313490.fastq.gz](https://github.com/galaxyproject/SARS-CoV-2/files/6722314/SRR11313490.fastq.gz)

**Comment by bgruening** [comment]
Let me know if you need more, we have a few more of them ;)

**Comment by bgruening** [comment]
I'm currently assembly a huge data drop from all accessions that @mvdbeek found. Where can store the data - its huge?

**Comment by bgruening** [comment]
Ok, real quick I could find ~3000 files. I know we have more, but this takes more time. You will find those files here ( ftp://xfer13.crg.eu/missing.tar ) its about 62 GB data. Please let me know when you have it and if I can delete them from the FTP. Please also know if its worth to spend a few hours on the other IDs. As we have a backup of more IDs we should be able to find them.

(its still copying, but I will get some sleep, you can start downloading in 2h from now I think)

**Comment by jbloom** [comment]
Thanks @bgruening. I just started copying these over from the FTP site.

If you happen to have more too, I can also align and analyze those of course.

**Comment by flodebarre** [comment]
Hi there, My aim when opening this issue was to help @jbloom (and others!) access more datasets if there are any. 
@bgruening @mvdbeek : thanks so much for your fantastic responsiveness and helpfulness -- you are amazing.

**Comment by bgruening** [comment]
@jbloom we should have essentially nearly all. Its just a matter of time, and time is limited as have our annual community conference starting today. Let me know if we can help further.

**Comment by jbloom** [comment]
@bgruening, I downloaded the TAR that you provided at `ftp://xfer13.crg.eu/missing.tar`. I got a total of 2013 files, the size of the TAR is 43G, and when unpacking after the 2013 files I got the error:
```
...
temp/ERR4206664_1.fastq.gz
tar: Unexpected EOF in archive
tar: rmtlseek not stopped at a record boundary
tar: Error is not recoverable: exiting now
``` 

So this makes me wonder if your process that was creating the TAR did not go to completion, since you indicated it should have ~3,000 files and be about ~62G?

In any case, let me know if you think the TAR is missing files and I can re-download a new version.

And yes, if you can find other missing SRR or ERRs, that would be great. Does Galaxy happen to have CRRs too? (I think this is prefix for the China BIGD database).

Also, do you happen to have old copies of SRR11119760 and SRR11119761? These are now on SRA, but I was still curious to look at original FASTQs.

Thanks for all this amazing help!

**Comment by bgruening** [comment]
@jbloom please try again. The upload probably failed at some point.

@jbloom we have TBs of data, if you have some IDs we can look them up, otherwise we need to different way to transfer data :)

**Comment by jbloom** [comment]
@bgruening, I was able to download the full TAR that you posted at  `ftp://xfer13.crg.eu/missing.tar`. Feel free to delete this file.

I would be interested in basically analyzed any accession that isn't in SRA, ENA, etc but is on Galaxy. If you send me a list of all accessions (ideally including CRR as well as SRR and ERR) on Galaxy, I could determine this list.

Alternatively, if it's easier for me to just set up some way to get them from Galaxy myself without you having to do anything, that would be great too. I am just not at all familiar with Galaxy so I have no idea how to search for the data available there and get it. Is it possible for me to somehow do that? If so, just feel free to point me to the instructions.

Thanks so much for all the help with this.

**Comment by bgruening** [comment]
Please see my mail .. I guess we can do the rest via mail. Thanks for opening the issue @flodebarre!

**Comment by flodebarre** [comment]
Happy to have put you in touch :-)
