### ISSUE TITLE
Building website locally

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/SARS-CoV-2#293]
Is this possible, and if so can someone provide a short guide?

**Comment by OlegZharkov** [comment]
hey @simonbray 
It's 
```yarn install```
```yarn develop```

**Comment by OlegZharkov** [comment]
https://github.com/galaxyproject/SARS-CoV-2/blob/master/CONTRIBUTING.md

**Comment by simonbray** [comment]
I should have seen that. Thanks a lot @OlegZharkov!
