### ISSUE TITLE
Little question about the datasets you used

### ISSUE THREAD

**Issue by saramonzon** [galaxyproject/SARS-CoV-2#45]
Hello there!
Great repo, it's being really useful!
One question though, we are downloading all raw data available at SRA, specially the project PRJNA607948, which provides sequences for both ONT and Illumina using SISPA protocol.
We are finding splitted R1 and R2 files with different number of reads when we download them with fastq-dump. Have you faced this problem? I've seen you have them marked as successfully analyzed. Maybe we are making some stupid mistake.
We don't obtain the same number as stated by the authors here (https://openresearch.labkey.com/wiki/ZEST/Ncov/page.view?name=SARS-CoV-2%20Deep%20Sequencing) either.
Thank you very much!

**Comment by saramonzon** [comment]
We have tried the download with fasterq-dump and now the R1 and R2 reads are even!! We still not get the exact number than the one reported by the authors but we can live with that.
But in case someone has this problem, you have to use sratools >= 2.9

Thanks!

**Comment by nathanhaigh** [comment]
When using `fastq-dump` you should include the `--split-3` option to put unpaired/orphaned reads into a separate file. Without it, you will have unpaired reads spread throughout your FASTQ files.

For example:

```bash
fastq-dump --split-files --split-3 SRR11140750
```

**Comment by bgruening** [comment]
@saramonzon you can also look at our workflows. We have also prepared histories with already downloaded datasets. See here: https://covid19.galaxyproject.org/1-PreProcessing/#alternate-workflow

**Comment by saramonzon** [comment]
Thank you very much! Happy to see that using --split-3 also does the work! We have already analyzed the data and we are exploring it at the moment!
Thanks for the resources!
