### ISSUE TITLE
Better cover page

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/SARS-CoV-2#63]
@bgruening we need to update front README wit summary of main findings. I'll do genomics part over the weekend. I want to prepare new release by Monday morning EU time.

**Comment by bgruening** [comment]
Ok, I will follow! :) Have a great weekend!

**Comment by dannon** [comment]
I worked on this a bit today actually; I can open a branch with the structure and work in any text you guys come up with

**Comment by jxtx** [comment]
Can we have the side bar even on the cover page? The content is a bit hidden on first load.

**Comment by nekrut** [comment]
@bgruening I meant the **main findings** not main funding.

**Comment by bgruening** [comment]
Lol, ok this is different. @dannon wanted also to work on some new layout. @nekrut any idea for a Genomic-image ... we could have two big images that will bring us to both projects.

**Comment by dannon** [comment]
Yeah, I didn't have a chance to get it done over the weekend, but something like this is what I'm working towards:
![image](https://user-images.githubusercontent.com/155398/77316409-c2354800-6cdf-11ea-9868-85d03a935936.png)

**Comment by dannon** [comment]
https://github.com/galaxyproject/SARS-CoV-2/pull/68 should close this out, swapping the cover page from a 'docs' style page to a wider layout with better styling.
