### ISSUE TITLE
Docker image doesn't appear to contain hg38

### ISSUE THREAD

**Issue by dhoconno** [galaxyproject/SARS-CoV-2#66]
Started Docker image as per:

https://covid19.galaxyproject.org/genomics/

with:

```
docker run -p 8080:80 quay.io/galaxy/covid-19-training
```

The initial workflow `1 - read pre-processing` won't run because minimap2 expects genome build, but can't find one. The error is: `Parameter ref_file requires a value, but has no legal values defined.`

Is hg38 included in the Docker image?

Thanks,

dave

**Comment by bedroesb** [comment]
@dhoconno thank you for pointing out this issue. The hg38 Genome is not included. I will tomorrow look into it and let you know when this is solved.

**Comment by bgruening** [comment]
@dhoconno can you start the container with `--privileged` and see if you see the reference data?

**Comment by bedroesb** [comment]
@dhoconno Could you try to rerun the analyses on this container image: quay.io/galaxy/covid-19-training:hg38 ?

**Comment by bedroesb** [comment]
The documentation concerning this is updated https://covid19.galaxyproject.org/genomics/deploy/#docker, so I think this issue can be closed.
