### ISSUE TITLE
MCRA workflow requires unspecified user input

### ISSUE THREAD

**Issue by wm75** [galaxyproject/SARS-CoV-2#7]
The current workflow version at https://github.com/galaxyproject/SARS-CoV-2/blob/master/MCRA/Galaxy-Workflow-MCRA.ga (and also the one on usegalaxy.org) won't run with just the accession and dates file as described, but ask to specify a `List of fields` for Step 4: Cut

It's not obvious what to set there.

**Comment by nekrut** [comment]
do not use this workflow. Use https://usegalaxy.org/u/aun1/w/mcra

**Comment by nekrut** [comment]
In fact, the ga file should be deleted from the repo

**Comment by wm75** [comment]
Yeah, tried also with the one on .org, but it has the same issue.
It's really just that you have to put in a `1` as a param for the Cut tool, but it's undocumented and probably confusing for someone new to Galaxy. Should be preset in the workflow.
