### ISSUE TITLE
Explain outputs and choice of tree in MCRA analysis

### ISSUE THREAD

**Issue by wm75** [galaxyproject/SARS-CoV-2#8]
1. The MCRA README has an empty Outputs section

    With the rather large number of datasets produced by IQ-TREE, an overview about what to expect would be nice. BTW, why is the consensus tree dataset empty?

2. I think it would be good to add a short rationale why the ipynb uses iqtree's BIONJ tree for further analysis, and not the MaxLikelihood tree. To me, at least, that seems like a surprising choice. The outputs section (see 1.) seems like a good place for this.

3. It would be great to mention where and how you can use the ipynb. It's probably in the manuscript, but it would be nice to have that info also in the repo itself.

**Comment by nekrut** [comment]
I will edit the README.md for clarity. Thank you for noticing all of this

**Comment by nekrut** [comment]
@wm75 you are correct. It should be ML output. I'll change the workflow and close the issue once done.

**Comment by nekrut** [comment]
This workflow now uses fasttree instead of iq-tree, which is an overkill for this particular scenario
